// examples/solid-acceptance/src/app/app.solid.tsx
/** @jsxImportSource @solidnative/platform/solid */
import { createEffect } from 'solid-js';
import { SafeAreaProvider } from '@solidnative/components';
import { ColorScheme, DeepLinks, HardwareBack, StatusBar, useService } from '@solidnative/device';
import { nativePlatform } from '@solidnative/fabric';
import {
  NativeStackOutlet,
  bindNativeNavigation,
  createNativeNavigation,
  type NativeNavigation,
} from '@solidnative/router';
import { routes } from './app.routes.solid.ts';

/**
 * The root component: a native stack whose first screen is the tab bar. Links
 * (`solidacceptance://detail/7`) and Android's back button drive the same navigation.
 */
export function App(props: { onNavigation?: (navigation: NativeNavigation) => void }) {
  const navigation = createNativeNavigation(routes);
  bindNativeNavigation(navigation, {
    links: useService(DeepLinks),
    back: useService(HardwareBack),
  });
  props.onNavigation?.(navigation);
  // Dark icons on a light screen and light on a dark one; Android draws them light otherwise.
  const scheme = useService(ColorScheme);
  const statusBar = useService(StatusBar);
  createEffect(() => statusBar.set({ style: scheme.current() === 'dark' ? 'light' : 'dark' }));
  // The class the Tailwind preset's ios: and android: variants match against.
  return (
    <SafeAreaProvider class={`platform-${nativePlatform()}`} style={{ flex: 1 }}>
      <NativeStackOutlet navigation={navigation} />
    </SafeAreaProvider>
  );
}

// examples/runs/src/app/app.solid.tsx
/** @jsxImportSource @solidnative/platform/solid */
import { SafeAreaProvider } from '@solidnative/components/solid';
import {
  DeepLinks,
  HardwareBack,
  ServiceScope,
  useService,
  type ServiceBinding,
} from '@solidnative/device/solid';
import {
  NativeStackOutlet,
  bindNativeNavigation,
  createNativeNavigation,
  type NativeNavigation,
} from '@solidnative/router/solid';
import { routes } from './app.routes.solid.ts';

/** The shell: a native stack, with the tab bar as its first screen. */
export function App(props: { navigation: NativeNavigation }) {
  return (
    <SafeAreaProvider style={{ flex: 1 }}>
      <NativeStackOutlet navigation={props.navigation} />
    </SafeAreaProvider>
  );
}

export interface RunsApplicationOptions {
  readonly services?: readonly ServiceBinding[];
  readonly initialPath?: string;
  readonly onError?: (error: unknown) => void;
  readonly onNavigation?: (navigation: NativeNavigation) => void;
}

/** One application scope owns the services, the retained screens, deep links and hardware back. */
export function RunsApplication(props: RunsApplicationOptions) {
  function Shell() {
    const navigation = createNativeNavigation(routes, { onError: props.onError });
    bindNativeNavigation(navigation, {
      links: useService(DeepLinks),
      back: useService(HardwareBack),
      initialPath: props.initialPath,
      onError: props.onError,
    });
    props.onNavigation?.(navigation);
    return <App navigation={navigation} />;
  }
  return (
    <ServiceScope services={props.services ?? []}>
      <Shell />
    </ServiceScope>
  );
}
